### ISSUE TITLE
expected type `orbclient::Window` found type `Box<orbclient::Window>` during compile

### ISSUE THREAD

**Issue by rjgoldsborough** [redox-os/sodium#57]
**Reproduction**: run "cargo run --features orbital"

**Expected behavior**: sodium runs

**Actual behavior**: compile fails with error.

```
src/state/editor.rs:188:21: 188:27 error: mismatched types [E0308]
src/state/editor.rs:188             window: window,
                                            ^~~~~~
src/state/editor.rs:188:21: 188:27 help: run `rustc --explain E0308` to see a detailed explanation
src/state/editor.rs:188:21: 188:27 note: expected type `orbclient::Window`
src/state/editor.rs:188:21: 188:27 note:    found type `Box<orbclient::Window>`
error: aborting due to previous error
error: Could not compile `sodium`.
```

**Misc**: 

The root of this issue seems to be that I only had orbclient 0.1.8 installed. 
I think this is what I got when I first ran Sodium. But since the dep is 0.1, I was not updated
to the newer versions and to the current 0.1.12 because only the patch version changed.

**Comment by jackpot51** [comment]
Yay
