### ISSUE TITLE
Photo in README does not appear

### ISSUE THREAD

**Issue by naltun** [redox-os/sodium#72]
The photo in the README for `sodium` does not appear, and the file redirects to a 404 page. The README specifies `https://github.com/redox-os/assets/raw/master/Sodium_logo.png` as the file link, but the logo appears to be [here](https://github.com/redox-os/assets/blob/master/logos/sodium/Sodium_logo.png) and in [raw form here](https://github.com/redox-os/assets/blob/master/logos/sodium/Sodium_logo.png?raw=true).

**Comment by sajattack** [comment]
It appears this was fixed in https://github.com/redox-os/sodium/pull/73 Could we close this issue?

**Comment by naltun** [comment]
Yep. Thanks for the update... I forgot all about it!
